# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8814ed078d67e906d1a472177117e94f64587a748dc23b1f9df89fe2d79f5b98ef855454e6e6525a4eda2d50add08526dd5c149fe3c787619fce7c9a29a80f92

test:
  secret_key_base: cc61133040cc8508d96133d8011e84afa104e5cb8af422ca8d257e87e2d760b746ef4385d0e319522ec44d9e6ec3e5d32813f6a21891898714b6376f361bd0a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
